from .base import CRUDBase
from .class_ import CRUDClass
from .leave import CRUDLeave
from .leave_type import CRUDLeaveType
from .lesson import CRUDLesson
from .role import CRUDRole
from .session import CRUDSession
from .status import CRUDStatus
from .user import CRUDUser
